### ISSUE TITLE
What does @pods symbol supposed to mean?

### ISSUE THREAD

**Issue by e-sung** [Ashton-W/cocoapods-update-if-you-dare#3]
Hi, it seems your plugin doesn't work on my environment. 
But if I remove the `@pods` condition from this [line](https://github.com/Ashton-W/cocoapods-update-if-you-dare/blob/af34bf2bd971d68737c2e7821ecdd88d8eeea7c6/lib/cocoapods_plugin.rb#L14), it works just fine.

What does this "@pods" symbol means? And why would this symbol break the plugin for just me? (Or is it just me?)
Googling with combinations of [Cocoapods, Plugin, @pods] didn't really worked out 😭 

Thank you for your amazing opensource project!

**Comment by e-sung** [comment]
I assume `@pods` symbol corresponds to dependency used in `pod update SomeDependency` method.. 
Becuase when I remove `@pods` symbol, the plugin shows dialog even if I run `pod udpate SomeDependency` method. 

But then, why would `@pods` symbol block the plugin when running simple `pod update`? 😭

**Comment by e-sung** [comment]
It seems recent version of Ruby has different logic evaluating `unless @pods` when @pods is empty 

```ruby 
// doesn't work
unless @pods  {
}

// works
unless (@pods.length > 0) {
}
```

**Comment by Ashton-W** [comment]
Hi there, what version of ruby and CocoaPods are you using?

**Comment by Ashton-W** [comment]
> I assume `@pods` symbol corresponds to dependency used in `pod update SomeDependency` method.

that’s correct, and there can be multiple pods and specified to update at once. 

Feel free to open a Pull Request and I can test it in my environment too

**Comment by e-sung** [comment]
I'm using ruby version 2.6.3, and cocoapods version 1.10.1
I'll open a Pull Request! Thank you for the response!
